### ISSUE TITLE
User link not generating correct path

### ISSUE THREAD

**Issue by saturnflyer** [jayroh/thredded#117]
thredded is creating a link to my user at `http://localhost:3000/users/Admin%20Admin` which sets the id to the first and last name "Admin Admin".

the code in this PR provides a scenario for this https://github.com/saturnflyer/purple_door/pull/44

**Comment by saturnflyer** [comment]
I realized that I should post some context around this.
Here's what config/routes.rb looks like
```ruby
  authenticate do
    mount Thredded::Engine => '/forum', as: :forum
    delete '/users/sign_out', as: :session, to: 'devise/sessions#destroy'
  end
```
We're using the `authenticate` routing helper from devise. I had to add the `delete` line to get the sign out link in thredded to work.
But it seems that thredded _should_ be creating a link to `http://localhost:3000/forum/users/Admin%20Admin`
Even though that user id is incorrect, I'm pointing out that it doesn't have `forum` in the path to the thredded profile.
If you pull that branch at purple_door, you can create message board, but then somehow the message board is `nil` when you go to the correct thredded profile path at `http://localhost:3000/forum/users/1`

**Comment by jayroh** [comment]
Great context there, sir. So ... here's the quick solution (I hope) to this.

https://github.com/jayroh/thredded/blob/master/lib/generators/thredded/install/templates/initializer.rb#L15

That config will let you customize that path. Since the engine doesn't hold the responsibility for displaying user information - delegating that to the parent application - I didn't want to scope it to inside of the engine.

That being said - was this config option a little buried? Would it have helped if it was bubbled up to the readme?

Talk to me Jim!

**Comment by glebm** [comment]
BTW, the app's routes can be accessed in the lambda via the global `Rails.application.routes.url_helpers`.

**Comment by saturnflyer** [comment]
Thanks @jayroh and @glebm. that was helpful. 
We have been rushing to get things together so I didn't take the time to study the initializer and just went with the defaults.

I suggest that you change the default to something like
```
Thredded.user_path = ->(user) { "/users/#{user.id}" }
```
or 
```
Thredded.user_path = ->(user) { "/users/#{user.to_param}" }
```

On thing that comes to mind with this is using the lambda in a different context.
For example if you use `instance_exec` then I would be able to use the lambda like the way it feels it should be used.
In the topics controller, for example, it uses the lambda like this
```ruby
user_path = Thredded.user_path(post.user)
```
But instead of requiring that I use the global `Rails.application.routes.url_helpers` I'd expect that I could write the typical path/url helpers
```ruby
Thredded.user_path = ->(user) { user_path(user) }
```
To support that, you could change the controller to use:
```ruby
user_path = view_context.instance_exec(user, &Thredded.user_path)
```

**Comment by glebm** [comment]
That's a great idea! :+1:

**Comment by jayroh** [comment]
@saturnflyer that's awesome stuff and I'm looking into doing this, however - I can't find the controller you're referring to. Could you point me to where you mean? Thank yoouuuu

@glebm that's a great idea too!

**Comment by saturnflyer** [comment]
@jayroh sorry. I looked quickly yesterday and thought it was a controller but it's the decorator
https://github.com/jayroh/thredded/blob/8337f12e78a25cc66707339beb7be5298ef467e0/app/decorators/thredded/post_decorator.rb#L20

**Comment by glebm** [comment]
Another nitpick: the decorator can provide a URL, but should not render any HTML, that's the job of the view.

**Comment by saturnflyer** [comment]
I found a place where the config wasn't used. Not sure if https://github.com/jayroh/thredded/pull/128 is the correct way to fix it... after creating the PR I realized that perhaps it should be in a decorator somewhere

**Comment by jayroh** [comment]
For now I'd say #128 is perfectly fine until it can make its way where it needs to be. Thank you @saturnflyer :)
