### ISSUE TITLE
consider directly scoping permissions to abilities

### ISSUE THREAD

**Issue by saturnflyer** [jayroh/thredded#118]
In this project https://github.com/saturnflyer/purple_door we happen to have defined a `can?` method which only accepts 1 argument.
When bringing thredded into the project, we inadvertently broke thredded authorization code from cancancan.
The thredded views blow up because our `can?` method overrides the one from this gem.
For now, I'm changing my theme views to use `current_ability.can?` but I suspect the easier option might be to change the main app to use a different method name.
Still, it might be better for thredded to use it's own abstraction like `thredded_can?` or something so that if I am using a `can?` method I'm not forced to change my app to fit the desires of thredded.
Just some food for thought...

**Comment by jayroh** [comment]
Excellent suggestion, Jim. I'm going to bump that up the chain for fixes.
Thank you!
