### ISSUE TITLE
missing /javascripts/thredded.js

### ISSUE THREAD

**Issue by saturnflyer** [jayroh/thredded#119]
I can't figure out where this is being requested

```
Started GET "/javascripts/thredded.js" for ::1 at 2015-08-03 10:27:20 -0400

ActionController::RoutingError (No route matches [GET] "/javascripts/thredded.js"):
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/jim/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/jim/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/jim/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by jayroh** [comment]
It might be looking for that in the layout (views/layouts/thredded.html.erb)

**Comment by saturnflyer** [comment]
Indeed it is! Should it be? I can't find that file in the project

**Comment by jayroh** [comment]
It should be there in /app/themes (that is, if you had run the theme
install generator). If not - it probably can't find it :/

In the gem it's in ->
`./spec/dummy/app/themes/default/assets/javascripts/thredded.es6`

Now that I look at this I'm thinking there's some weird assumptions I made
with the theme stuff.  Maybe it should all go into /app/thredded_themes or
/app/thredded/themes or maybe just /app/views/thredded/theme/* ?

Thoughts?

This is all awesome feedback, by the way Jim. It's bubbling up a lot of
weird assumptions I made

**Comment by saturnflyer** [comment]
I followed the readme and ran `rails generate thredded:themes`.
It looks like I do have it in `app/themes/default/assets/javascripts/thredded/thredded.es6` but my app isn't looking there for it

**Comment by saturnflyer** [comment]
I added a line to my thredded initializer (locally) `puts Rails.application.config.assets.paths` and got this

```
/Users/jim/Projects/purple_door/app/assets/images
/Users/jim/Projects/purple_door/app/assets/javascripts
/Users/jim/Projects/purple_door/app/assets/stylesheets
/Users/jim/.gem/ruby/2.2.2/gems/neat-1.7.2/app/assets/stylesheets
/Users/jim/.gem/ruby/2.2.2/gems/bourbon-4.2.3/app/assets/stylesheets
/Users/jim/.gem/ruby/2.2.2/gems/gravtastic-3.2.6/vendor/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/bundler/gems/thredded-39da38c744ab/app/assets/images
/Users/jim/.gem/ruby/2.2.2/bundler/gems/thredded-39da38c744ab/app/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/bundler/gems/thredded-39da38c744ab/app/assets/stylesheets
/Users/jim/.gem/ruby/2.2.2/gems/momentjs-rails-2.10.3/vendor/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/foundation-rails-5.5.2.1/vendor/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/foundation-rails-5.5.2.1/vendor/assets/stylesheets
/Users/jim/.gem/ruby/2.2.2/gems/turbolinks-2.5.3/lib/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/jquery-rails-4.0.4/vendor/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/coffee-rails-4.1.0/lib/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/foundation-datetimepicker-rails-0.2.1/vendor/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/foundation-datetimepicker-rails-0.2.1/vendor/assets/stylesheets
```

Somehow, `app/themes` is not added

**Comment by saturnflyer** [comment]
Here's how I got past this problem:
I changed the name of the file to `thredded.es6.js` and altered my local layout to use `<%= javascript_include_tag 'thredded.es6' %>`

After that, the file loads, but there is a JS error _i think_ because it's not being compiled properly with the vendor libraries... maybe?:
`Unexpected use of reserved word 'class'` and `Can't find variable: Thredded`

The contents of the generated file (`assets/thredded.es6.self-4eb9403c5dab522100b806a0514b50c5fd65d86674ea1ac1e065771ec54a1659.js?body=1`) consist entirely of:

```js
class Thredded {
  constructor() {
    this.topicForm = new ThreddedTopicForm();
    this.privateTopicForm = new ThreddedPrivateTopicForm();
    this.postForm = new ThreddedPostForm();
    this.kbShortcuts = new ThreddedKeyboardShortcuts();
    this.timestamps = new ThreddedTimeStamps();
    this.searchBar = new ThreddedSearchBar();
    this.currentlyOnline = new ThreddedCurrentlyOnline();
  }
}

Thredded.new = function(){ return new Thredded; }
```

**Comment by saturnflyer** [comment]
I still get the same errors, but after changing all of the `es6` files to `.es6.js` the app now actually loads them but errors with `Unexpected use of reserved word 'class'`

**Comment by jayroh** [comment]
In your config -

`Thredded.theme = :default`

Is that in there?

**Comment by saturnflyer** [comment]
I had `Thredded.theme = :default` but it was commented out.
I uncommented it (my theme *is* in app/themes/default) but it made no change in behavior

**Comment by jayroh** [comment]
Hmmmmmm.

What does `Rails.configuration.assets.paths` say? Is the path in there?

The engine initializer should be pushing some paths into asset and view
paths. See here:

https://github.com/jayroh/thredded/blob/master/lib/thredded/engine.rb

FWIW that's just about to change too ... I have a branch that's pushing all
those paths in ONLY if the theme is set.

**Comment by jayroh** [comment]
@saturnflyer is this app open sourced? If so I can pull it down and give a hand.

**Comment by saturnflyer** [comment]
Yes it is! the forum branch uses thredded and is here https://github.com/saturnflyer/purple_door/tree/forum

**Comment by saturnflyer** [comment]
Oh. my asset paths are listed above. I dug into the engine code to see what was missing and tried to add them manually in my thredded initializer (in the main app) but it didn't appear to change anything.

here are my asset paths again:
```
/Users/jim/Projects/purple_door/app/assets/images
/Users/jim/Projects/purple_door/app/assets/javascripts
/Users/jim/Projects/purple_door/app/assets/stylesheets
/Users/jim/.gem/ruby/2.2.2/gems/neat-1.7.2/app/assets/stylesheets
/Users/jim/.gem/ruby/2.2.2/gems/bourbon-4.2.3/app/assets/stylesheets
/Users/jim/.gem/ruby/2.2.2/gems/gravtastic-3.2.6/vendor/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/bundler/gems/thredded-39da38c744ab/app/assets/images
/Users/jim/.gem/ruby/2.2.2/bundler/gems/thredded-39da38c744ab/app/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/bundler/gems/thredded-39da38c744ab/app/assets/stylesheets
/Users/jim/.gem/ruby/2.2.2/gems/momentjs-rails-2.10.3/vendor/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/foundation-rails-5.5.2.1/vendor/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/foundation-rails-5.5.2.1/vendor/assets/stylesheets
/Users/jim/.gem/ruby/2.2.2/gems/turbolinks-2.5.3/lib/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/jquery-rails-4.0.4/vendor/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/coffee-rails-4.1.0/lib/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/foundation-datetimepicker-rails-0.2.1/vendor/assets/javascripts
/Users/jim/.gem/ruby/2.2.2/gems/foundation-datetimepicker-rails-0.2.1/vendor/assets/stylesheets
```

**Comment by jayroh** [comment]
Duh. Missed the asset paths the first time. 

![](https://s-media-cache-ak0.pinimg.com/originals/95/66/7f/95667ff99bbaa9c349a3d4230916f052.gif)

**Comment by glebm** [comment]
`/app/views/thredded/theme/*` would be more appropriate for Rails (engine views go in app/views/engine). Would also be nice to take them from the gem instead of copying (for that it suffices to place them under the same path in the gem).

**Comment by jayroh** [comment]
Closing this particular issue but opening a new one with details on moving the theme files to a more sane location.

Thanks @glebm and @saturnflyer!
