### ISSUE TITLE
configuring message board types

### ISSUE THREAD

**Issue by saturnflyer** [jayroh/thredded#120]
my project is using thredded as an admin only feature. When going in to configure what type of message board to create, the options for public/private/members/anonymous/etc will be redundant for me. is there a way to configure Thredded to select only one? 
My current thought is to just hard-code the type I want in a theme view.
Or am I missing some other option or idea for handling message board security?

**Comment by jayroh** [comment]
@saturnflyer For now the best bet would be to edit `app/themes/default/views/thredded/messageboards/new.html.erb` and change the drop-down to a hidden form field with the one static option you would like.

If there was a way to override asking for this would you expect a config option to override it globally and not display this field in the form at all? Just curious.

**Comment by saturnflyer** [comment]
I'm not really sure. I added thredded, saw the interface and thought: "oh, that's something to consider". We'll probably do the hidden field thing for now

**Comment by jayroh** [comment]
Ok that sounds good.

I've considered simplifying the types of messageboards entirely, actually, to something like just "private" and "public". I get the feeling those are the only two that *really* get a lot of use but I'll leave it open for discussion.
