### ISSUE TITLE
Drop support for MRI < 2.2, test with JRuby

### ISSUE THREAD

**Issue by glebm** [jayroh/thredded#133]
Can we drop support for MRI < 2.2? The upgrade path from 2.0 to 2.2 is super-smooth, so I would expect everyone to upgrade by the time we release (esp. given the massive performance benefits of 2.2 from RGenGC and frozen string literals). This will let us use required keyword arguments throughout.

We can also test with JRuby as it is a popular implementation and its compatibility is very good.

**Comment by glebm** [comment]
Tried adding jRuby support here: https://github.com/glebm/thredded/commit/f515ea8e5495ef6267a0a168f5dad382e6ecd6dd. The current blockers are github-markdown and sanitize (nokogumbo dep).

**Comment by jayroh** [comment]
I don't see why not re: bumping it all up to 2.2. Could you spit up the commit mentioned to one for the switch to just 2.2 and one WIP for jruby support? I'm not familiar with github-markdown's dependencies - is there some C extension stuff going on in there?
