### ISSUE TITLE
Avatar support in Who's online

### ISSUE THREAD

**Issue by glebm** [jayroh/thredded#137]
Avatars currently rely on Gravtastic that we have to put on some model, that is currently Post, meaning we can't display these where there is no Post. Need to use a gem that doesn't require associating with a model, e.g. https://github.com/Wixel/ruby-gravatar

**Comment by jayroh** [comment]
Hey, I really like that! Much better, indeed

**Comment by glebm** [comment]
Done.

**Comment by jayroh** [comment]
🌪GLEB-NADO🌪
