### ISSUE TITLE
Forem to Thredded migration questions

### ISSUE THREAD

**Issue by glebm** [jayroh/thredded#37]
I am working on a Forem to Thredded migration.

Questions about some columns:

* thredded_topics
  * `type` - is this obsolete?
* thredded_posts
  * `user_email` - ~~denormalized? what if the user changes their email?~~ addressed in #41
  * `source` - is this used? should this perhaps be set to `'forem'`?

Still figuring out how Thredded does moderation -- noticed a roles table but no state columns on things.

Forem handles moderation like this:
* Topics and posts have a `state` column which can be `approved`, `pending_review`, or `spam`.
* The first content a user posts does not get published until it is moderated. Then, the user's `forem_state` column is set to either `approved` or `spam` and all of their content gets the same value.

Here is the initial version https://github.com/jayroh/thredded/wiki/Migrate-from-Forem

**Comment by jayroh** [comment]
See [this page in the wiki](https://github.com/jayroh/thredded/wiki/Migrate-from-Forem) for more information
