### ISSUE TITLE
Roles: everyone is a member

### ISSUE THREAD

**Issue by glebm** [jayroh/thredded#43]
In my app, all messageboards have `posting_permission` set to `logged_in`. However, when creating a private topic, the list of users is taken from Roles. Is this a bug?

Also, when creating a private topic in the demo app, the only user I can add is joel.

**Comment by jayroh** [comment]
Just ran into this on the `meta` messageboard on thredded.com where I @ message'd someone who is *not* a member, and it didn't notify them. Best user story I can think of right now is

> As a user who posts on a completely public messageboard I want my @ mentions to notify me.
