### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by glebm** [jayroh/thredded#46]
Thank you for a great engine! :grin: :beers:  As I dig deeper into the code, I am really impressed with the quality, and believe this has all the potential to do for Rails what phpbb did for PHP: i.e. an awesome, extensible, de-facto standard forum. I've dumped some thoughts below.

---

#### Themes

Themes should not override view files, instead they should be pure CSS and some configuration. The major advantage is zero-maintenance updates and ease of theming. Here is why this is possible:

1. Modern CSS allows complete control over layout. Even without flexbox, `table-header/footer` group and `float` tricks allow swapping top/bottom and left/right elements (like in my [bootstrap theme](https://github.com/jayroh/thredded/wiki/Bootstrap-Sass-Styles)).

2. simple_form allows complete control over form rendering with just configuration. #32

3. Hooks can be used for extension, paving a way for plugins.

#### One way to do this

* [x] Split the views need into many little partials, with classes on everything. Provide hooks for extension - I've done this in my [rails_email_preview](https://github.com/glebm/rails_email_preview) gem and it seems to work very well.
* [x] Move HTML generation out of helpers and into partials. E.g. move the timestamp helper to `app/views/thredded/shared/_timestamp.html.slim`.
* [x] Provide JavaScript, as it is an inseparable part of a modern webapp. #5 
* [ ] I18n everything. I wrote the [i18n-tasks](https://github.com/glebm/i18n-tasks) gem to make maintaining locale files super-easy.
* [ ] Have 2 completely different themes to validate the "ease of theming" bit.

---

It would be awesome to get this out of the stealth mode sooner rather than later, as there are lots of potential contributors out there: forem is lacking in scope, and Discourse fills a different niche as it's not an engine but a full app, while Thredded hits the sweet :candy: spot :dart:. I can help spread the word  :loudspeaker:.

:sunrise_over_mountains: :sunrise: :sunny:

**Comment by jayroh** [comment]
@glebm @kirantpatil starting on this in earnest. Step 1 is mostly working to get things split out into appropriate partials and adding a generator to copy all the partials to a parent app if it's so desired.
