### ISSUE TITLE
Rails 3 app support

### ISSUE THREAD

**Issue by kirantpatil** [jayroh/thredded#55]
Is it possible to use thredded with rails 3 app ?

**Comment by jayroh** [comment]
Hi @kirantpatil - it is not. When I got around to extracting the message board stuff out to to an engine/gem 4.0 had just come out so I concentrated on everything working with 4.0+.  The best I can do right now is to encourage you to try to get it supported with 3.0 and send some pull requests. I don't use rails 3 for any of the apps I work on so I can't devote the time to it, sorry!
