### ISSUE TITLE
[theme] Namespace the theme css to `.thredded-*`

### ISSUE THREAD

**Issue by jayroh** [jayroh/thredded#81]
This would keep the css from clashing with any defined for the parent application

**Comment by jayroh** [comment]
See issue #77 for further discussion

**Comment by glebm** [comment]
Note that you can do nested imports in Sass to have the namespace prepended automatically:

```module.sass
.thredded {
  @import 'dependency';
}
```

``sass
&-thing {
  color: red;
}
```

```css
.thredded-thing {
  color: red;
}
```

**Comment by jayroh** [comment]
Fancy!

**Comment by glebm** [comment]
A small part of it is done in #135, e.g. see https://github.com/glebm/thredded/blob/layout-js/app/assets/stylesheets/thredded.scss and https://github.com/glebm/thredded/blob/layout-js/app/assets/stylesheets/thredded/layout/_main-navigation.scss.

**Comment by glebm** [comment]
Sass variables should also be scoped. Also neat/bourbon are really unfriendly to scoping the styles, but the theme does not seem to rely heavily on them, so perhaps they can be dropped easily.

**Comment by jayroh** [comment]
> Also neat/bourbon are really unfriendly to scoping the styles

Yeah? I wasn't aware of that. Could you provide an example because I'm not sure I entirely know what you mean

**Comment by glebm** [comment]
1. Unscoped mixins such as `media` are likely to clash with the user's mixins.
2. Styles on `body` mean we can't do a namespaced import.
3. Unscoped styles on bare tags such as `h1, button` mean we must to do an unscoped import, but 2.

**Comment by glebm** [comment]
Done!
