### ISSUE TITLE
[theme] Open and close "Currently Online"

### ISSUE THREAD

**Issue by kylefiedler** [jayroh/thredded#86]
When I am interested to see if there are any other people online, I want to reveal the list of people online, so that I might strike up a conversation with them.

When I am not interested in who else is online, I want to hide the people who are currently online, so that it won't take up extra space on the screen.

**Comment by kylefiedler** [comment]
@jayroh I have no idea what I'm doing with es6 and I don't think you want me writing plain ol' javascript

**Comment by jayroh** [comment]
@kylefiedler PR #100 is a start to tackling this
