### ISSUE TITLE
Users page

### ISSUE THREAD

**Issue by kylefiedler** [jayroh/thredded#96]
Getting an error on /users/:id

```No route matches [GET] "/users/kylefiedler"

Rails.root: /Users/kyle/Development/thredded/spec/dummy
```

**Comment by jayroh** [comment]
Good catch! I'll tackle this one

**Comment by jayroh** [comment]
Just thought about this a little bit and came to the realization that this will end up being a page in the **parent** app that the developer(s) will have to use. I'll stub it out for us but it'll be super light, and "not our problem"(tm)(c).

**Comment by kylefiedler** [comment]
Yea I was actually thinking that we could probably pull it out from the top navigation. I'm down for what ever you think would be best.

**Comment by jayroh** [comment]
Easy enough to remedy here w/pull #103
